server {
    listen 80;
    root /usr/share/nginx/html;
    charset utf-8;
    gzip on;
    gzip_types text/css application/javascript image/svg+xml;

    location = /index.html { add_header Cache-Control "no-cache"; }
    location ~* \.(svg|png|css)$ { add_header Cache-Control "public, max-age=604800"; }
    location ~* \.woff2$ { add_header Cache-Control "public, max-age=31536000, immutable"; }
    location / { try_files $uri $uri/ /index.html; }
}
