"""Build the English expression list from Wiktionary categories.

Run inside the api container:
    docker compose run --rm -v ./api/scripts:/app/scripts api python scripts/build_expressions.py

Writes app/languages/en/data/expressions.txt (one expression per line, dictionary form).
Data from Wiktionary, CC BY-SA 4.0.
"""

import re
import time
from pathlib import Path

import httpx

API = "https://en.wiktionary.org/w/api.php"
CATEGORIES = ["English idioms", "English phrases", "English prepositional phrases"]
OUT = Path(__file__).resolve().parents[1] / "app" / "languages" / "en" / "data" / "expressions.txt"
# Wikimedia's bot policy requires a User-Agent with a way to reach the operator.
HEADERS = {"User-Agent": "glosa-expression-builder/0.1 (https://github.com/CoKeFish/glosa) python-httpx"}
# Plain lowercase English words, spaces, apostrophes and hyphens; at least two words.
VALID = re.compile(r"^[a-z][a-z'’\-]*( [a-z'’\-]+)+$")


def members(client: httpx.Client, category: str) -> list[str]:
    titles, params = [], {"action": "query", "list": "categorymembers", "cmtitle": f"Category:{category}",
                          "cmlimit": "500", "cmnamespace": "0", "format": "json"}
    while True:
        data = client.get(API, params=params).json()
        titles += [m["title"] for m in data["query"]["categorymembers"]]
        if "continue" not in data:
            return titles
        params.update(data["continue"])
        time.sleep(0.2)  # be polite to the Wikimedia API


ARTICLES = {"the", "a", "an"}


def main() -> None:
    by_category: dict[str, set[str]] = {}
    with httpx.Client(headers=HEADERS, timeout=60) as client:
        for category in CATEGORIES:
            titles = members(client, category)
            by_category[category] = {t.replace("’", "'") for t in titles if VALID.match(t)}
            print(f"{category}: {len(titles)} entries, {len(by_category[category])} usable")

    idioms = by_category["English idioms"]
    # Prepositional phrases with an article ("on the floor", "in the air") are nearly always
    # literal in running text; keep them only when Wiktionary also lists them as idioms.
    prepositional = {
        p for p in by_category["English prepositional phrases"]
        if p in idioms or not ARTICLES & set(p.split())
    }
    print(f"prepositional phrases kept: {len(prepositional)}")
    found = idioms | by_category["English phrases"] | prepositional
    header = ("# English expressions (idioms, phrases, prepositional phrases) from Wiktionary, CC BY-SA 4.0.\n"
              "# Generated by scripts/build_expressions.py; do not edit by hand.\n")
    OUT.write_text(header + "\n".join(sorted(found)) + "\n", encoding="utf-8")
    print(f"wrote {len(found)} expressions to {OUT}")


if __name__ == "__main__":
    main()
