"""baseline: schema of 0.1.0

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 02:33:27.415409
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_at'), 'ai_usage', ['at'], unique=False)
    op.create_table('api_keys',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted', sa.Text(), nullable=False),
    sa.Column('hint', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('audio_cache',
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dictionary_cache',
    sa.Column('key', sa.String(length=400), nullable=False),
    sa.Column('entries', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('offline_entries',
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('lines', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('source', 'word')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('speech_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('srs_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('srs_step', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'key')
    )
    op.create_index(op.f('ix_terms_language'), 'terms', ['language'], unique=False)
    op.create_table('translation_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('translator', sa.String(length=120), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tokens', sa.JSON(), nullable=False),
    sa.Column('units', sa.JSON(), nullable=False),
    sa.Column('grammar', sa.JSON(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_book_id'), 'sections', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_book_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_table('translation_cache')
    op.drop_index(op.f('ix_terms_language'), table_name='terms')
    op.drop_table('terms')
    op.drop_table('speech_cache')
    op.drop_table('settings')
    op.drop_table('offline_entries')
    op.drop_table('dictionary_cache')
    op.drop_table('books')
    op.drop_table('audio_cache')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_usage_at'), table_name='ai_usage')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
