"""drills: syllabus, rounds, items, error tags

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-07 04:50:16.300136
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('syllabus_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_practiced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllabus_topics_user_id'), 'syllabus_topics', ['user_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('closing_note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_user_id'), 'rounds', ['user_id'], unique=False)
    op.create_table('round_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('spanish', sa.Text(), nullable=False),
    sa.Column('topic_ids', sa.JSON(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('failed_topic_ids', sa.JSON(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round_items_round_id'), 'round_items', ['round_id'], unique=False)
    op.create_table('round_item_errors',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['round_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['error_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round_item_errors')
    op.drop_index(op.f('ix_round_items_round_id'), table_name='round_items')
    op.drop_table('round_items')
    op.drop_index(op.f('ix_rounds_user_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_syllabus_topics_user_id'), table_name='syllabus_topics')
    op.drop_table('syllabus_topics')
    op.drop_table('error_tags')
    # ### end Alembic commands ###
